# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
    ports:
      - '5432:${POSTGRES_PORT}'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8090
